# Generated by Django 3.2.3 on 2021-06-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('art_text', models.TextField(verbose_name='Статья')),
                ('art_date_pub', models.DateTimeField(verbose_name='Дата публиации статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сom_autor', models.CharField(max_length=30, verbose_name='Автор комментария')),
                ('com_text', models.CharField(max_length=100, verbose_name='Текст комментария')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_s.art')),
            ],
        ),
    ]
